#!/bin/sh
set -eu

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IOS_PROJECT_DIR="$PROJECT_ROOT/ios/App"
IOS_WORKSPACE="${IOS_WORKSPACE:-App.xcworkspace}"
IOS_SCHEME="${IOS_SCHEME:-App}"
IOS_CONFIGURATION="${IOS_CONFIGURATION:-Release}"
IOS_ARCHIVE_PATH="${IOS_ARCHIVE_PATH:-$PROJECT_ROOT/ios/build/App.xcarchive}"
IOS_CODE_SIGN_STYLE="${IOS_CODE_SIGN_STYLE:-Automatic}"
IOS_CODE_SIGNING_ALLOWED="${IOS_CODE_SIGNING_ALLOWED:-YES}"
IOS_DEVELOPMENT_TEAM="${IOS_DEVELOPMENT_TEAM:-}"
IOS_PROVISIONING_PROFILE_SPECIFIER="${IOS_PROVISIONING_PROFILE_SPECIFIER:-}"
IOS_SIGNING_IDENTITY="${IOS_SIGNING_IDENTITY:-}"

mkdir -p "$(dirname "$IOS_ARCHIVE_PATH")"

cd "$IOS_PROJECT_DIR"

set -- xcodebuild -workspace "$IOS_WORKSPACE" -scheme "$IOS_SCHEME" -configuration "$IOS_CONFIGURATION" -destination "generic/platform=iOS" -archivePath "$IOS_ARCHIVE_PATH" archive

set -- "$@" CODE_SIGN_STYLE="$IOS_CODE_SIGN_STYLE"
set -- "$@" CODE_SIGNING_ALLOWED="$IOS_CODE_SIGNING_ALLOWED"

if [ -n "$IOS_DEVELOPMENT_TEAM" ]; then
  set -- "$@" DEVELOPMENT_TEAM="$IOS_DEVELOPMENT_TEAM"
fi

if [ -n "$IOS_PROVISIONING_PROFILE_SPECIFIER" ]; then
  set -- "$@" PROVISIONING_PROFILE_SPECIFIER="$IOS_PROVISIONING_PROFILE_SPECIFIER"
fi

if [ -n "$IOS_SIGNING_IDENTITY" ]; then
  set -- "$@" CODE_SIGN_IDENTITY="$IOS_SIGNING_IDENTITY"
fi

"$@"
